services:
  mongodb:
    image: mongo:7
    container_name: whereabout-mongodb
    restart: unless-stopped
    ports:
      - '27018:27017'
    volumes:
      - mongodb_data:/data/db

  mailpit:
    image: axllent/mailpit:latest
    container_name: whereabout-mailpit
    restart: unless-stopped
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  mongodb_data:
